/* Generated By:JavaCC: Do not edit this line. TestParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TestParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int CURVEDBRACKETOPEN = 6;
  /** RegularExpression Id. */
  int CURVEDBRACKETCLOSE = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int ASIGN = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int BRACEOPEN = 13;
  /** RegularExpression Id. */
  int BRACECLOSE = 14;
  /** RegularExpression Id. */
  int BYREF = 15;
  /** RegularExpression Id. */
  int BYVAL = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int NOTEQUALS = 25;
  /** RegularExpression Id. */
  int LOWER = 26;
  /** RegularExpression Id. */
  int LOWEROREQUAL = 27;
  /** RegularExpression Id. */
  int GREATER = 28;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 29;
  /** RegularExpression Id. */
  int PLUS = 30;
  /** RegularExpression Id. */
  int MINUS = 31;
  /** RegularExpression Id. */
  int MULTIPLY = 32;
  /** RegularExpression Id. */
  int DIVIDE = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int IDENT = 37;
  /** RegularExpression Id. */
  int NUMBER = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\"(\"",
    "\")\"",
    "\"byref\"",
    "\"byval\"",
    "\",\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "<LETTER>",
    "<DIGIT>",
    "<IDENT>",
    "<NUMBER>",
  };

}
